language: ruby
before_install: gem install bundler -v '~> 1.6.0' --no-ri --no-rdoc
rvm:
  - 2.3

env:
  - PUPPET_VERSION="4"

branches:
  only:
    - master
    - develop

script:
  - 'bundle exec rake lint'
  - 'bundle exec rake rspec'
