name          'vStone-accounts'
version       '0.1.0'
source        'git://github.com/vStone/puppet-accounts.git'
author        'Jan Vansteenkiste <jan@vstone.eu>'
license       'Apache License, Version 2.0'
summary       'Manage your (system) user accounts in hiera'
description   'Splits up user management in different structures and combines them all to manage users'
project_page  'https://github.com/vStone/puppet-accounts'
